language: cpp
os: linux
dist: bionic

services:
  - docker

before_install:
  - docker build --tag eselparser ./ci

script:
  - docker run --interactive --tty --rm --volume $(pwd):$(pwd) --workdir $(pwd) eselparser ./bootstrap.sh
  - docker run --interactive --tty --rm --volume $(pwd):$(pwd) --workdir $(pwd) eselparser ./configure
  - docker run --interactive --tty --rm --volume $(pwd):$(pwd) --workdir $(pwd) eselparser make -j4
  - docker run --interactive --tty --rm --volume $(pwd):$(pwd) --workdir $(pwd) eselparser make check-valgrind
